insert into `t1ship` (`code`,`name`,`weig`,`birth`) values('DD32','',1324,1985);
insert into `t1ship` (`code`,`name`,`weig`,`birth`) values('CV05','',25200,1988);
insert into `t1ship` (`code`,`name`,`weig`,`birth`) values('CV06','',33500,1989);
insert into `t1ship` (`code`,`name`,`weig`,`birth`) values('BB14','',39254,1983);
insert into `t1ship` (`code`,`name`,`weig`,`birth`) values('BB15','',46852,1987);
insert into `t1ship` (`code`,`name`,`weig`,`birth`) values('BB16','',45852,1987);

insert into `dct_noun` (`word`, `claz`, `lang`, `type`) values('China','','en','full');
insert into `dct_noun` (`word`, `claz`, `lang`, `type`) values('CHN','','en','abbr');
insert into `dct_noun` (`word`, `claz`, `lang`, `type`) values('CN','','en','abbr');
insert into `dct_noun` (`word`, `claz`, `lang`, `type`) values('fdu','','en','abbr');
insert into `dct_noun` (`word`, `claz`, `lang`, `type`) values('fudan','','en','full');
insert into `dct_noun` (`word`, `claz`, `lang`, `type`) values('SH','','en','abbr');
insert into `dct_noun` (`word`, `claz`, `lang`, `type`) values('Shanghai','','en','full');
insert into `dct_noun` (`word`, `claz`, `lang`, `type`) values('上海','','zh','full');
insert into `dct_noun` (`word`, `claz`, `lang`, `type`) values('中国','',NULL,NULL);
insert into `dct_noun` (`word`, `claz`, `lang`, `type`) values('县级行政区','','zh',NULL);
insert into `dct_noun` (`word`, `claz`, `lang`, `type`) values('国家','','zh',NULL);
insert into `dct_noun` (`word`, `claz`, `lang`, `type`) values('地级行政区','','zh',NULL);
insert into `dct_noun` (`word`, `claz`, `lang`, `type`) values('复旦','','zh','abbr');
insert into `dct_noun` (`word`, `claz`, `lang`, `type`) values('复旦大学','','zh','full');
insert into `dct_noun` (`word`, `claz`, `lang`, `type`) values('沪','','zh','abbr');
insert into `dct_noun` (`word`, `claz`, `lang`, `type`) values('省级行政区','','zh',NULL);
insert into `dct_noun` (`word`, `claz`, `lang`, `type`) values('魔都','','zh','surn');

insert into `dct_rel` (`subject`, `verb`, `object`, `adverb` ) values('Chine','EQ','China',NULL);
insert into `dct_rel` (`subject`, `verb`, `object`, `adverb` ) values('中国','EQ','China',NULL);
insert into `dct_rel` (`subject`, `verb`, `object`, `adverb` ) values('中华人民共和国','EQ','China','ALMOST');
insert into `dct_rel` (`subject`, `verb`, `object`, `adverb` ) values('县级行政区','PARTOF','地级行政区',NULL);
insert into `dct_rel` (`subject`, `verb`, `object`, `adverb` ) values('地级行政区','PARTOF','省级行政区',NULL);
insert into `dct_rel` (`subject`, `verb`, `object`, `adverb` ) values('上海','ONEOF','省级行政区',NULL);
insert into `dct_rel` (`subject`, `verb`, `object`, `adverb` ) values('江苏','ONEOF','省级行政区',NULL);
insert into `dct_rel` (`subject`, `verb`, `object`, `adverb` ) values('复旦大学','ONEOF','大学',NULL);
insert into `dct_rel` (`subject`, `verb`, `object`, `adverb` ) values('大学','KINDOF','学校',NULL);
insert into `dct_rel` (`subject`, `verb`, `object`, `adverb` ) values('中学','KINDOF','学校',NULL);
insert into `dct_rel` (`subject`, `verb`, `object`, `adverb` ) values('复旦大学','IN','上海','ALMOST');
insert into `dct_rel` (`subject`, `verb`, `object`, `adverb` ) values('魔都','EQ','上海','ALAIS');
insert into `dct_rel` (`subject`, `verb`, `object`, `adverb` ) values('沪','EQ','上海','ALIAS');
insert into `dct_rel` (`subject`, `verb`, `object`, `adverb` ) values('Shanghai','EQ','上海',NULL);
INSERT INTO `dct_rel` (`subject`, `verb`, `object`, `adverb` ) VALUES('南京市','PARTOF','江苏',NULL);
INSERT INTO `dct_rel` (`subject`, `verb`, `object`, `adverb` ) VALUES('扬州市','PARTOF','江苏',NULL);
INSERT INTO `dct_rel` (`subject`, `verb`, `object`, `adverb` ) VALUES('泰州市','PARTOF','江苏',NULL);
INSERT INTO `dct_rel` (`subject`, `verb`, `object`, `adverb` ) VALUES('镇江市','PARTOF','江苏',NULL);
INSERT INTO `dct_rel` (`subject`, `verb`, `object`, `adverb` ) VALUES('苏州市','PARTOF','江苏',NULL);
INSERT INTO `dct_rel` (`subject`, `verb`, `object`, `adverb` ) VALUES('杨浦区','PARTOF','上海',NULL);
INSERT INTO `dct_rel` (`subject`, `verb`, `object`, `adverb` ) VALUES('黄浦区','PARTOF','上海',NULL);
INSERT INTO `dct_rel` (`subject`, `verb`, `object`, `adverb` ) VALUES('闵行区','PARTOF','上海',NULL);
INSERT INTO `dct_rel` (`subject`, `verb`, `object`, `adverb` ) VALUES('浦东新区','PARTOF','上海',NULL);